include ../Makefile.global

OBJ = adaption_field.o MPEG_transport_stream.o program_association_section.o transport_packet.o PES_packet.o CA_section.o CA_descriptor.o

all: $(OBJ)

clean:
	rm *.o & true
