include ../../Makefile.global

OBJ = adaption_field.o MPEG_transport_stream.o program_association_section.o transport_packet.o PES_packet.o CA_section.o CA_descriptor.o TS_program_map_section.o descriptor.o ARIB_caption_statement.o ARIB_caption_management.o ARIB_data_group.o ARIB_data_unit.o

all: $(OBJ)

clean:
	rm *.o || true
